# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/administrator/DQN/Arcade-Learning-Environment-2.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/administrator/DQN/Arcade-Learning-Environment-2.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/administrator/DQN/Arcade-Learning-Environment-2.0/CMakeFiles /home/administrator/DQN/Arcade-Learning-Environment-2.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/administrator/DQN/Arcade-Learning-Environment-2.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ale-bin

# Build rule for target.
ale-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ale-bin
.PHONY : ale-bin

# fast build rule for target.
ale-bin/fast:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/build
.PHONY : ale-bin/fast

#=============================================================================
# Target rules for targets named ale-c-lib

# Build rule for target.
ale-c-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ale-c-lib
.PHONY : ale-c-lib

# fast build rule for target.
ale-c-lib/fast:
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/build
.PHONY : ale-c-lib/fast

#=============================================================================
# Target rules for targets named ale-lib

# Build rule for target.
ale-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ale-lib
.PHONY : ale-lib

# fast build rule for target.
ale-lib/fast:
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/build
.PHONY : ale-lib/fast

#=============================================================================
# Target rules for targets named sharedLibraryInterfaceExample

# Build rule for target.
sharedLibraryInterfaceExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharedLibraryInterfaceExample
.PHONY : sharedLibraryInterfaceExample

# fast build rule for target.
sharedLibraryInterfaceExample/fast:
	$(MAKE) -f CMakeFiles/sharedLibraryInterfaceExample.dir/build.make CMakeFiles/sharedLibraryInterfaceExample.dir/build
.PHONY : sharedLibraryInterfaceExample/fast

#=============================================================================
# Target rules for targets named videoRecordingExample

# Build rule for target.
videoRecordingExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videoRecordingExample
.PHONY : videoRecordingExample

# fast build rule for target.
videoRecordingExample/fast:
	$(MAKE) -f CMakeFiles/videoRecordingExample.dir/build.make CMakeFiles/videoRecordingExample.dir/build
.PHONY : videoRecordingExample/fast

ale_python_interface/ale_c_wrapper.o: ale_python_interface/ale_c_wrapper.cpp.o
.PHONY : ale_python_interface/ale_c_wrapper.o

# target to build an object file
ale_python_interface/ale_c_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.o
.PHONY : ale_python_interface/ale_c_wrapper.cpp.o

ale_python_interface/ale_c_wrapper.i: ale_python_interface/ale_c_wrapper.cpp.i
.PHONY : ale_python_interface/ale_c_wrapper.i

# target to preprocess a source file
ale_python_interface/ale_c_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.i
.PHONY : ale_python_interface/ale_c_wrapper.cpp.i

ale_python_interface/ale_c_wrapper.s: ale_python_interface/ale_c_wrapper.cpp.s
.PHONY : ale_python_interface/ale_c_wrapper.s

# target to generate assembly for a file
ale_python_interface/ale_c_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.s
.PHONY : ale_python_interface/ale_c_wrapper.cpp.s

doc/examples/sharedLibraryInterfaceExample.o: doc/examples/sharedLibraryInterfaceExample.cpp.o
.PHONY : doc/examples/sharedLibraryInterfaceExample.o

# target to build an object file
doc/examples/sharedLibraryInterfaceExample.cpp.o:
	$(MAKE) -f CMakeFiles/sharedLibraryInterfaceExample.dir/build.make CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
.PHONY : doc/examples/sharedLibraryInterfaceExample.cpp.o

doc/examples/sharedLibraryInterfaceExample.i: doc/examples/sharedLibraryInterfaceExample.cpp.i
.PHONY : doc/examples/sharedLibraryInterfaceExample.i

# target to preprocess a source file
doc/examples/sharedLibraryInterfaceExample.cpp.i:
	$(MAKE) -f CMakeFiles/sharedLibraryInterfaceExample.dir/build.make CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.i
.PHONY : doc/examples/sharedLibraryInterfaceExample.cpp.i

doc/examples/sharedLibraryInterfaceExample.s: doc/examples/sharedLibraryInterfaceExample.cpp.s
.PHONY : doc/examples/sharedLibraryInterfaceExample.s

# target to generate assembly for a file
doc/examples/sharedLibraryInterfaceExample.cpp.s:
	$(MAKE) -f CMakeFiles/sharedLibraryInterfaceExample.dir/build.make CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.s
.PHONY : doc/examples/sharedLibraryInterfaceExample.cpp.s

doc/examples/videoRecordingExample.o: doc/examples/videoRecordingExample.cpp.o
.PHONY : doc/examples/videoRecordingExample.o

# target to build an object file
doc/examples/videoRecordingExample.cpp.o:
	$(MAKE) -f CMakeFiles/videoRecordingExample.dir/build.make CMakeFiles/videoRecordingExample.dir/doc/examples/videoRecordingExample.cpp.o
.PHONY : doc/examples/videoRecordingExample.cpp.o

doc/examples/videoRecordingExample.i: doc/examples/videoRecordingExample.cpp.i
.PHONY : doc/examples/videoRecordingExample.i

# target to preprocess a source file
doc/examples/videoRecordingExample.cpp.i:
	$(MAKE) -f CMakeFiles/videoRecordingExample.dir/build.make CMakeFiles/videoRecordingExample.dir/doc/examples/videoRecordingExample.cpp.i
.PHONY : doc/examples/videoRecordingExample.cpp.i

doc/examples/videoRecordingExample.s: doc/examples/videoRecordingExample.cpp.s
.PHONY : doc/examples/videoRecordingExample.s

# target to generate assembly for a file
doc/examples/videoRecordingExample.cpp.s:
	$(MAKE) -f CMakeFiles/videoRecordingExample.dir/build.make CMakeFiles/videoRecordingExample.dir/doc/examples/videoRecordingExample.cpp.s
.PHONY : doc/examples/videoRecordingExample.cpp.s

src/ale_interface.o: src/ale_interface.cpp.o
.PHONY : src/ale_interface.o

# target to build an object file
src/ale_interface.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/ale_interface.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/ale_interface.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/ale_interface.cpp.o
.PHONY : src/ale_interface.cpp.o

src/ale_interface.i: src/ale_interface.cpp.i
.PHONY : src/ale_interface.i

# target to preprocess a source file
src/ale_interface.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/ale_interface.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/ale_interface.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/ale_interface.cpp.i
.PHONY : src/ale_interface.cpp.i

src/ale_interface.s: src/ale_interface.cpp.s
.PHONY : src/ale_interface.s

# target to generate assembly for a file
src/ale_interface.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/ale_interface.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/ale_interface.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/ale_interface.cpp.s
.PHONY : src/ale_interface.cpp.s

src/common/AleException.o: src/common/AleException.cpp.o
.PHONY : src/common/AleException.o

# target to build an object file
src/common/AleException.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/AleException.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/AleException.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/AleException.cpp.o
.PHONY : src/common/AleException.cpp.o

src/common/AleException.i: src/common/AleException.cpp.i
.PHONY : src/common/AleException.i

# target to preprocess a source file
src/common/AleException.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/AleException.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/AleException.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/AleException.cpp.i
.PHONY : src/common/AleException.cpp.i

src/common/AleException.s: src/common/AleException.cpp.s
.PHONY : src/common/AleException.s

# target to generate assembly for a file
src/common/AleException.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/AleException.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/AleException.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/AleException.cpp.s
.PHONY : src/common/AleException.cpp.s

src/common/ColourPalette.o: src/common/ColourPalette.cpp.o
.PHONY : src/common/ColourPalette.o

# target to build an object file
src/common/ColourPalette.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ColourPalette.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ColourPalette.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ColourPalette.cpp.o
.PHONY : src/common/ColourPalette.cpp.o

src/common/ColourPalette.i: src/common/ColourPalette.cpp.i
.PHONY : src/common/ColourPalette.i

# target to preprocess a source file
src/common/ColourPalette.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ColourPalette.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ColourPalette.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ColourPalette.cpp.i
.PHONY : src/common/ColourPalette.cpp.i

src/common/ColourPalette.s: src/common/ColourPalette.cpp.s
.PHONY : src/common/ColourPalette.s

# target to generate assembly for a file
src/common/ColourPalette.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ColourPalette.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ColourPalette.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ColourPalette.cpp.s
.PHONY : src/common/ColourPalette.cpp.s

src/common/Constants.o: src/common/Constants.cpp.o
.PHONY : src/common/Constants.o

# target to build an object file
src/common/Constants.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Constants.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Constants.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Constants.cpp.o
.PHONY : src/common/Constants.cpp.o

src/common/Constants.i: src/common/Constants.cpp.i
.PHONY : src/common/Constants.i

# target to preprocess a source file
src/common/Constants.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Constants.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Constants.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Constants.cpp.i
.PHONY : src/common/Constants.cpp.i

src/common/Constants.s: src/common/Constants.cpp.s
.PHONY : src/common/Constants.s

# target to generate assembly for a file
src/common/Constants.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Constants.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Constants.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Constants.cpp.s
.PHONY : src/common/Constants.cpp.s

src/common/Log.o: src/common/Log.cpp.o
.PHONY : src/common/Log.o

# target to build an object file
src/common/Log.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Log.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Log.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Log.cpp.o
.PHONY : src/common/Log.cpp.o

src/common/Log.i: src/common/Log.cpp.i
.PHONY : src/common/Log.i

# target to preprocess a source file
src/common/Log.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Log.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Log.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Log.cpp.i
.PHONY : src/common/Log.cpp.i

src/common/Log.s: src/common/Log.cpp.s
.PHONY : src/common/Log.s

# target to generate assembly for a file
src/common/Log.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/Log.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/Log.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/Log.cpp.s
.PHONY : src/common/Log.cpp.s

src/common/ScreenExporter.o: src/common/ScreenExporter.cpp.o
.PHONY : src/common/ScreenExporter.o

# target to build an object file
src/common/ScreenExporter.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ScreenExporter.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ScreenExporter.cpp.o
.PHONY : src/common/ScreenExporter.cpp.o

src/common/ScreenExporter.i: src/common/ScreenExporter.cpp.i
.PHONY : src/common/ScreenExporter.i

# target to preprocess a source file
src/common/ScreenExporter.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ScreenExporter.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ScreenExporter.cpp.i
.PHONY : src/common/ScreenExporter.cpp.i

src/common/ScreenExporter.s: src/common/ScreenExporter.cpp.s
.PHONY : src/common/ScreenExporter.s

# target to generate assembly for a file
src/common/ScreenExporter.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/ScreenExporter.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/ScreenExporter.cpp.s
.PHONY : src/common/ScreenExporter.cpp.s

src/common/SoundExporter.o: src/common/SoundExporter.cpp.o
.PHONY : src/common/SoundExporter.o

# target to build an object file
src/common/SoundExporter.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundExporter.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundExporter.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundExporter.cpp.o
.PHONY : src/common/SoundExporter.cpp.o

src/common/SoundExporter.i: src/common/SoundExporter.cpp.i
.PHONY : src/common/SoundExporter.i

# target to preprocess a source file
src/common/SoundExporter.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundExporter.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundExporter.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundExporter.cpp.i
.PHONY : src/common/SoundExporter.cpp.i

src/common/SoundExporter.s: src/common/SoundExporter.cpp.s
.PHONY : src/common/SoundExporter.s

# target to generate assembly for a file
src/common/SoundExporter.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundExporter.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundExporter.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundExporter.cpp.s
.PHONY : src/common/SoundExporter.cpp.s

src/common/SoundNull.o: src/common/SoundNull.cxx.o
.PHONY : src/common/SoundNull.o

# target to build an object file
src/common/SoundNull.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundNull.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundNull.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundNull.cxx.o
.PHONY : src/common/SoundNull.cxx.o

src/common/SoundNull.i: src/common/SoundNull.cxx.i
.PHONY : src/common/SoundNull.i

# target to preprocess a source file
src/common/SoundNull.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundNull.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundNull.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundNull.cxx.i
.PHONY : src/common/SoundNull.cxx.i

src/common/SoundNull.s: src/common/SoundNull.cxx.s
.PHONY : src/common/SoundNull.s

# target to generate assembly for a file
src/common/SoundNull.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundNull.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundNull.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundNull.cxx.s
.PHONY : src/common/SoundNull.cxx.s

src/common/SoundSDL.o: src/common/SoundSDL.cxx.o
.PHONY : src/common/SoundSDL.o

# target to build an object file
src/common/SoundSDL.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundSDL.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundSDL.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundSDL.cxx.o
.PHONY : src/common/SoundSDL.cxx.o

src/common/SoundSDL.i: src/common/SoundSDL.cxx.i
.PHONY : src/common/SoundSDL.i

# target to preprocess a source file
src/common/SoundSDL.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundSDL.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundSDL.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundSDL.cxx.i
.PHONY : src/common/SoundSDL.cxx.i

src/common/SoundSDL.s: src/common/SoundSDL.cxx.s
.PHONY : src/common/SoundSDL.s

# target to generate assembly for a file
src/common/SoundSDL.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/SoundSDL.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/SoundSDL.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/SoundSDL.cxx.s
.PHONY : src/common/SoundSDL.cxx.s

src/common/display_screen.o: src/common/display_screen.cpp.o
.PHONY : src/common/display_screen.o

# target to build an object file
src/common/display_screen.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/display_screen.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.o
.PHONY : src/common/display_screen.cpp.o

src/common/display_screen.i: src/common/display_screen.cpp.i
.PHONY : src/common/display_screen.i

# target to preprocess a source file
src/common/display_screen.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/display_screen.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.i
.PHONY : src/common/display_screen.cpp.i

src/common/display_screen.s: src/common/display_screen.cpp.s
.PHONY : src/common/display_screen.s

# target to generate assembly for a file
src/common/display_screen.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/common/display_screen.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.s
.PHONY : src/common/display_screen.cpp.s

src/controllers/ale_controller.o: src/controllers/ale_controller.cpp.o
.PHONY : src/controllers/ale_controller.o

# target to build an object file
src/controllers/ale_controller.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/ale_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/ale_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/ale_controller.cpp.o
.PHONY : src/controllers/ale_controller.cpp.o

src/controllers/ale_controller.i: src/controllers/ale_controller.cpp.i
.PHONY : src/controllers/ale_controller.i

# target to preprocess a source file
src/controllers/ale_controller.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/ale_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/ale_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/ale_controller.cpp.i
.PHONY : src/controllers/ale_controller.cpp.i

src/controllers/ale_controller.s: src/controllers/ale_controller.cpp.s
.PHONY : src/controllers/ale_controller.s

# target to generate assembly for a file
src/controllers/ale_controller.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/ale_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/ale_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/ale_controller.cpp.s
.PHONY : src/controllers/ale_controller.cpp.s

src/controllers/fifo_controller.o: src/controllers/fifo_controller.cpp.o
.PHONY : src/controllers/fifo_controller.o

# target to build an object file
src/controllers/fifo_controller.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/fifo_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/fifo_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/fifo_controller.cpp.o
.PHONY : src/controllers/fifo_controller.cpp.o

src/controllers/fifo_controller.i: src/controllers/fifo_controller.cpp.i
.PHONY : src/controllers/fifo_controller.i

# target to preprocess a source file
src/controllers/fifo_controller.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/fifo_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/fifo_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/fifo_controller.cpp.i
.PHONY : src/controllers/fifo_controller.cpp.i

src/controllers/fifo_controller.s: src/controllers/fifo_controller.cpp.s
.PHONY : src/controllers/fifo_controller.s

# target to generate assembly for a file
src/controllers/fifo_controller.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/fifo_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/fifo_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/fifo_controller.cpp.s
.PHONY : src/controllers/fifo_controller.cpp.s

src/controllers/rlglue_controller.o: src/controllers/rlglue_controller.cpp.o
.PHONY : src/controllers/rlglue_controller.o

# target to build an object file
src/controllers/rlglue_controller.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/rlglue_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/rlglue_controller.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/rlglue_controller.cpp.o
.PHONY : src/controllers/rlglue_controller.cpp.o

src/controllers/rlglue_controller.i: src/controllers/rlglue_controller.cpp.i
.PHONY : src/controllers/rlglue_controller.i

# target to preprocess a source file
src/controllers/rlglue_controller.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/rlglue_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/rlglue_controller.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/rlglue_controller.cpp.i
.PHONY : src/controllers/rlglue_controller.cpp.i

src/controllers/rlglue_controller.s: src/controllers/rlglue_controller.cpp.s
.PHONY : src/controllers/rlglue_controller.s

# target to generate assembly for a file
src/controllers/rlglue_controller.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/controllers/rlglue_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/controllers/rlglue_controller.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/controllers/rlglue_controller.cpp.s
.PHONY : src/controllers/rlglue_controller.cpp.s

src/environment/AleSystem.o: src/environment/AleSystem.cxx.o
.PHONY : src/environment/AleSystem.o

# target to build an object file
src/environment/AleSystem.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/AleSystem.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/AleSystem.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/AleSystem.cxx.o
.PHONY : src/environment/AleSystem.cxx.o

src/environment/AleSystem.i: src/environment/AleSystem.cxx.i
.PHONY : src/environment/AleSystem.i

# target to preprocess a source file
src/environment/AleSystem.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/AleSystem.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/AleSystem.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/AleSystem.cxx.i
.PHONY : src/environment/AleSystem.cxx.i

src/environment/AleSystem.s: src/environment/AleSystem.cxx.s
.PHONY : src/environment/AleSystem.s

# target to generate assembly for a file
src/environment/AleSystem.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/AleSystem.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/AleSystem.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/AleSystem.cxx.s
.PHONY : src/environment/AleSystem.cxx.s

src/environment/Deserializer.o: src/environment/Deserializer.cxx.o
.PHONY : src/environment/Deserializer.o

# target to build an object file
src/environment/Deserializer.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Deserializer.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Deserializer.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Deserializer.cxx.o
.PHONY : src/environment/Deserializer.cxx.o

src/environment/Deserializer.i: src/environment/Deserializer.cxx.i
.PHONY : src/environment/Deserializer.i

# target to preprocess a source file
src/environment/Deserializer.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Deserializer.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Deserializer.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Deserializer.cxx.i
.PHONY : src/environment/Deserializer.cxx.i

src/environment/Deserializer.s: src/environment/Deserializer.cxx.s
.PHONY : src/environment/Deserializer.s

# target to generate assembly for a file
src/environment/Deserializer.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Deserializer.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Deserializer.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Deserializer.cxx.s
.PHONY : src/environment/Deserializer.cxx.s

src/environment/FSNode.o: src/environment/FSNode.cxx.o
.PHONY : src/environment/FSNode.o

# target to build an object file
src/environment/FSNode.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/FSNode.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/FSNode.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/FSNode.cxx.o
.PHONY : src/environment/FSNode.cxx.o

src/environment/FSNode.i: src/environment/FSNode.cxx.i
.PHONY : src/environment/FSNode.i

# target to preprocess a source file
src/environment/FSNode.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/FSNode.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/FSNode.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/FSNode.cxx.i
.PHONY : src/environment/FSNode.cxx.i

src/environment/FSNode.s: src/environment/FSNode.cxx.s
.PHONY : src/environment/FSNode.s

# target to generate assembly for a file
src/environment/FSNode.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/FSNode.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/FSNode.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/FSNode.cxx.s
.PHONY : src/environment/FSNode.cxx.s

src/environment/Random.o: src/environment/Random.cxx.o
.PHONY : src/environment/Random.o

# target to build an object file
src/environment/Random.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Random.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Random.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Random.cxx.o
.PHONY : src/environment/Random.cxx.o

src/environment/Random.i: src/environment/Random.cxx.i
.PHONY : src/environment/Random.i

# target to preprocess a source file
src/environment/Random.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Random.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Random.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Random.cxx.i
.PHONY : src/environment/Random.cxx.i

src/environment/Random.s: src/environment/Random.cxx.s
.PHONY : src/environment/Random.s

# target to generate assembly for a file
src/environment/Random.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Random.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Random.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Random.cxx.s
.PHONY : src/environment/Random.cxx.s

src/environment/RetroAgent.o: src/environment/RetroAgent.cpp.o
.PHONY : src/environment/RetroAgent.o

# target to build an object file
src/environment/RetroAgent.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/RetroAgent.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/RetroAgent.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/RetroAgent.cpp.o
.PHONY : src/environment/RetroAgent.cpp.o

src/environment/RetroAgent.i: src/environment/RetroAgent.cpp.i
.PHONY : src/environment/RetroAgent.i

# target to preprocess a source file
src/environment/RetroAgent.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/RetroAgent.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/RetroAgent.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/RetroAgent.cpp.i
.PHONY : src/environment/RetroAgent.cpp.i

src/environment/RetroAgent.s: src/environment/RetroAgent.cpp.s
.PHONY : src/environment/RetroAgent.s

# target to generate assembly for a file
src/environment/RetroAgent.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/RetroAgent.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/RetroAgent.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/RetroAgent.cpp.s
.PHONY : src/environment/RetroAgent.cpp.s

src/environment/Serializer.o: src/environment/Serializer.cxx.o
.PHONY : src/environment/Serializer.o

# target to build an object file
src/environment/Serializer.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Serializer.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Serializer.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Serializer.cxx.o
.PHONY : src/environment/Serializer.cxx.o

src/environment/Serializer.i: src/environment/Serializer.cxx.i
.PHONY : src/environment/Serializer.i

# target to preprocess a source file
src/environment/Serializer.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Serializer.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Serializer.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Serializer.cxx.i
.PHONY : src/environment/Serializer.cxx.i

src/environment/Serializer.s: src/environment/Serializer.cxx.s
.PHONY : src/environment/Serializer.s

# target to generate assembly for a file
src/environment/Serializer.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Serializer.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Serializer.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Serializer.cxx.s
.PHONY : src/environment/Serializer.cxx.s

src/environment/Settings.o: src/environment/Settings.cxx.o
.PHONY : src/environment/Settings.o

# target to build an object file
src/environment/Settings.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Settings.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Settings.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Settings.cxx.o
.PHONY : src/environment/Settings.cxx.o

src/environment/Settings.i: src/environment/Settings.cxx.i
.PHONY : src/environment/Settings.i

# target to preprocess a source file
src/environment/Settings.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Settings.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Settings.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Settings.cxx.i
.PHONY : src/environment/Settings.cxx.i

src/environment/Settings.s: src/environment/Settings.cxx.s
.PHONY : src/environment/Settings.s

# target to generate assembly for a file
src/environment/Settings.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/Settings.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/Settings.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/Settings.cxx.s
.PHONY : src/environment/Settings.cxx.s

src/environment/ale_state.o: src/environment/ale_state.cpp.o
.PHONY : src/environment/ale_state.o

# target to build an object file
src/environment/ale_state.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/ale_state.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/ale_state.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/ale_state.cpp.o
.PHONY : src/environment/ale_state.cpp.o

src/environment/ale_state.i: src/environment/ale_state.cpp.i
.PHONY : src/environment/ale_state.i

# target to preprocess a source file
src/environment/ale_state.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/ale_state.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/ale_state.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/ale_state.cpp.i
.PHONY : src/environment/ale_state.cpp.i

src/environment/ale_state.s: src/environment/ale_state.cpp.s
.PHONY : src/environment/ale_state.s

# target to generate assembly for a file
src/environment/ale_state.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/ale_state.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/ale_state.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/ale_state.cpp.s
.PHONY : src/environment/ale_state.cpp.s

src/environment/phosphor_blend.o: src/environment/phosphor_blend.cpp.o
.PHONY : src/environment/phosphor_blend.o

# target to build an object file
src/environment/phosphor_blend.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/phosphor_blend.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/phosphor_blend.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/phosphor_blend.cpp.o
.PHONY : src/environment/phosphor_blend.cpp.o

src/environment/phosphor_blend.i: src/environment/phosphor_blend.cpp.i
.PHONY : src/environment/phosphor_blend.i

# target to preprocess a source file
src/environment/phosphor_blend.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/phosphor_blend.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/phosphor_blend.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/phosphor_blend.cpp.i
.PHONY : src/environment/phosphor_blend.cpp.i

src/environment/phosphor_blend.s: src/environment/phosphor_blend.cpp.s
.PHONY : src/environment/phosphor_blend.s

# target to generate assembly for a file
src/environment/phosphor_blend.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/phosphor_blend.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/phosphor_blend.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/phosphor_blend.cpp.s
.PHONY : src/environment/phosphor_blend.cpp.s

src/environment/retro_environment.o: src/environment/retro_environment.cpp.o
.PHONY : src/environment/retro_environment.o

# target to build an object file
src/environment/retro_environment.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/retro_environment.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/retro_environment.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/retro_environment.cpp.o
.PHONY : src/environment/retro_environment.cpp.o

src/environment/retro_environment.i: src/environment/retro_environment.cpp.i
.PHONY : src/environment/retro_environment.i

# target to preprocess a source file
src/environment/retro_environment.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/retro_environment.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/retro_environment.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/retro_environment.cpp.i
.PHONY : src/environment/retro_environment.cpp.i

src/environment/retro_environment.s: src/environment/retro_environment.cpp.s
.PHONY : src/environment/retro_environment.s

# target to generate assembly for a file
src/environment/retro_environment.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/environment/retro_environment.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/environment/retro_environment.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/environment/retro_environment.cpp.s
.PHONY : src/environment/retro_environment.cpp.s

src/external/TinyMT/tinymt32.o: src/external/TinyMT/tinymt32.c.o
.PHONY : src/external/TinyMT/tinymt32.o

# target to build an object file
src/external/TinyMT/tinymt32.c.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/external/TinyMT/tinymt32.c.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/external/TinyMT/tinymt32.c.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/external/TinyMT/tinymt32.c.o
.PHONY : src/external/TinyMT/tinymt32.c.o

src/external/TinyMT/tinymt32.i: src/external/TinyMT/tinymt32.c.i
.PHONY : src/external/TinyMT/tinymt32.i

# target to preprocess a source file
src/external/TinyMT/tinymt32.c.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/external/TinyMT/tinymt32.c.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/external/TinyMT/tinymt32.c.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/external/TinyMT/tinymt32.c.i
.PHONY : src/external/TinyMT/tinymt32.c.i

src/external/TinyMT/tinymt32.s: src/external/TinyMT/tinymt32.c.s
.PHONY : src/external/TinyMT/tinymt32.s

# target to generate assembly for a file
src/external/TinyMT/tinymt32.c.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/external/TinyMT/tinymt32.c.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/external/TinyMT/tinymt32.c.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/external/TinyMT/tinymt32.c.s
.PHONY : src/external/TinyMT/tinymt32.c.s

src/games/AtariSettings.o: src/games/AtariSettings.cpp.o
.PHONY : src/games/AtariSettings.o

# target to build an object file
src/games/AtariSettings.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/AtariSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/AtariSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/AtariSettings.cpp.o
.PHONY : src/games/AtariSettings.cpp.o

src/games/AtariSettings.i: src/games/AtariSettings.cpp.i
.PHONY : src/games/AtariSettings.i

# target to preprocess a source file
src/games/AtariSettings.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/AtariSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/AtariSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/AtariSettings.cpp.i
.PHONY : src/games/AtariSettings.cpp.i

src/games/AtariSettings.s: src/games/AtariSettings.cpp.s
.PHONY : src/games/AtariSettings.s

# target to generate assembly for a file
src/games/AtariSettings.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/AtariSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/AtariSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/AtariSettings.cpp.s
.PHONY : src/games/AtariSettings.cpp.s

src/games/RomSettings.o: src/games/RomSettings.cpp.o
.PHONY : src/games/RomSettings.o

# target to build an object file
src/games/RomSettings.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomSettings.cpp.o
.PHONY : src/games/RomSettings.cpp.o

src/games/RomSettings.i: src/games/RomSettings.cpp.i
.PHONY : src/games/RomSettings.i

# target to preprocess a source file
src/games/RomSettings.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomSettings.cpp.i
.PHONY : src/games/RomSettings.cpp.i

src/games/RomSettings.s: src/games/RomSettings.cpp.s
.PHONY : src/games/RomSettings.s

# target to generate assembly for a file
src/games/RomSettings.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomSettings.cpp.s
.PHONY : src/games/RomSettings.cpp.s

src/games/RomUtils.o: src/games/RomUtils.cpp.o
.PHONY : src/games/RomUtils.o

# target to build an object file
src/games/RomUtils.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomUtils.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomUtils.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomUtils.cpp.o
.PHONY : src/games/RomUtils.cpp.o

src/games/RomUtils.i: src/games/RomUtils.cpp.i
.PHONY : src/games/RomUtils.i

# target to preprocess a source file
src/games/RomUtils.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomUtils.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomUtils.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomUtils.cpp.i
.PHONY : src/games/RomUtils.cpp.i

src/games/RomUtils.s: src/games/RomUtils.cpp.s
.PHONY : src/games/RomUtils.s

# target to generate assembly for a file
src/games/RomUtils.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/RomUtils.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/RomUtils.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/RomUtils.cpp.s
.PHONY : src/games/RomUtils.cpp.s

src/games/Roms.o: src/games/Roms.cpp.o
.PHONY : src/games/Roms.o

# target to build an object file
src/games/Roms.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/Roms.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/Roms.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/Roms.cpp.o
.PHONY : src/games/Roms.cpp.o

src/games/Roms.i: src/games/Roms.cpp.i
.PHONY : src/games/Roms.i

# target to preprocess a source file
src/games/Roms.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/Roms.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/Roms.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/Roms.cpp.i
.PHONY : src/games/Roms.cpp.i

src/games/Roms.s: src/games/Roms.cpp.s
.PHONY : src/games/Roms.s

# target to generate assembly for a file
src/games/Roms.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/Roms.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/Roms.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/Roms.cpp.s
.PHONY : src/games/Roms.cpp.s

src/games/SnesSettings.o: src/games/SnesSettings.cpp.o
.PHONY : src/games/SnesSettings.o

# target to build an object file
src/games/SnesSettings.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/SnesSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/SnesSettings.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/SnesSettings.cpp.o
.PHONY : src/games/SnesSettings.cpp.o

src/games/SnesSettings.i: src/games/SnesSettings.cpp.i
.PHONY : src/games/SnesSettings.i

# target to preprocess a source file
src/games/SnesSettings.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/SnesSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/SnesSettings.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/SnesSettings.cpp.i
.PHONY : src/games/SnesSettings.cpp.i

src/games/SnesSettings.s: src/games/SnesSettings.cpp.s
.PHONY : src/games/SnesSettings.s

# target to generate assembly for a file
src/games/SnesSettings.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/SnesSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/SnesSettings.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/SnesSettings.cpp.s
.PHONY : src/games/SnesSettings.cpp.s

src/games/supported/AtariCollection.o: src/games/supported/AtariCollection.cpp.o
.PHONY : src/games/supported/AtariCollection.o

# target to build an object file
src/games/supported/AtariCollection.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/AtariCollection.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/AtariCollection.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/AtariCollection.cpp.o
.PHONY : src/games/supported/AtariCollection.cpp.o

src/games/supported/AtariCollection.i: src/games/supported/AtariCollection.cpp.i
.PHONY : src/games/supported/AtariCollection.i

# target to preprocess a source file
src/games/supported/AtariCollection.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/AtariCollection.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/AtariCollection.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/AtariCollection.cpp.i
.PHONY : src/games/supported/AtariCollection.cpp.i

src/games/supported/AtariCollection.s: src/games/supported/AtariCollection.cpp.s
.PHONY : src/games/supported/AtariCollection.s

# target to generate assembly for a file
src/games/supported/AtariCollection.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/AtariCollection.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/AtariCollection.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/AtariCollection.cpp.s
.PHONY : src/games/supported/AtariCollection.cpp.s

src/games/supported/Boxing.o: src/games/supported/Boxing.cpp.o
.PHONY : src/games/supported/Boxing.o

# target to build an object file
src/games/supported/Boxing.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Boxing.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Boxing.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Boxing.cpp.o
.PHONY : src/games/supported/Boxing.cpp.o

src/games/supported/Boxing.i: src/games/supported/Boxing.cpp.i
.PHONY : src/games/supported/Boxing.i

# target to preprocess a source file
src/games/supported/Boxing.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Boxing.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Boxing.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Boxing.cpp.i
.PHONY : src/games/supported/Boxing.cpp.i

src/games/supported/Boxing.s: src/games/supported/Boxing.cpp.s
.PHONY : src/games/supported/Boxing.s

# target to generate assembly for a file
src/games/supported/Boxing.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Boxing.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Boxing.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Boxing.cpp.s
.PHONY : src/games/supported/Boxing.cpp.s

src/games/supported/Breakout.o: src/games/supported/Breakout.cpp.o
.PHONY : src/games/supported/Breakout.o

# target to build an object file
src/games/supported/Breakout.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Breakout.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Breakout.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Breakout.cpp.o
.PHONY : src/games/supported/Breakout.cpp.o

src/games/supported/Breakout.i: src/games/supported/Breakout.cpp.i
.PHONY : src/games/supported/Breakout.i

# target to preprocess a source file
src/games/supported/Breakout.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Breakout.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Breakout.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Breakout.cpp.i
.PHONY : src/games/supported/Breakout.cpp.i

src/games/supported/Breakout.s: src/games/supported/Breakout.cpp.s
.PHONY : src/games/supported/Breakout.s

# target to generate assembly for a file
src/games/supported/Breakout.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Breakout.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Breakout.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Breakout.cpp.s
.PHONY : src/games/supported/Breakout.cpp.s

src/games/supported/MortalKombat.o: src/games/supported/MortalKombat.cpp.o
.PHONY : src/games/supported/MortalKombat.o

# target to build an object file
src/games/supported/MortalKombat.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/MortalKombat.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/MortalKombat.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/MortalKombat.cpp.o
.PHONY : src/games/supported/MortalKombat.cpp.o

src/games/supported/MortalKombat.i: src/games/supported/MortalKombat.cpp.i
.PHONY : src/games/supported/MortalKombat.i

# target to preprocess a source file
src/games/supported/MortalKombat.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/MortalKombat.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/MortalKombat.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/MortalKombat.cpp.i
.PHONY : src/games/supported/MortalKombat.cpp.i

src/games/supported/MortalKombat.s: src/games/supported/MortalKombat.cpp.s
.PHONY : src/games/supported/MortalKombat.s

# target to generate assembly for a file
src/games/supported/MortalKombat.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/MortalKombat.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/MortalKombat.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/MortalKombat.cpp.s
.PHONY : src/games/supported/MortalKombat.cpp.s

src/games/supported/Seaquest.o: src/games/supported/Seaquest.cpp.o
.PHONY : src/games/supported/Seaquest.o

# target to build an object file
src/games/supported/Seaquest.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Seaquest.cpp.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Seaquest.cpp.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Seaquest.cpp.o
.PHONY : src/games/supported/Seaquest.cpp.o

src/games/supported/Seaquest.i: src/games/supported/Seaquest.cpp.i
.PHONY : src/games/supported/Seaquest.i

# target to preprocess a source file
src/games/supported/Seaquest.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Seaquest.cpp.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Seaquest.cpp.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Seaquest.cpp.i
.PHONY : src/games/supported/Seaquest.cpp.i

src/games/supported/Seaquest.s: src/games/supported/Seaquest.cpp.s
.PHONY : src/games/supported/Seaquest.s

# target to generate assembly for a file
src/games/supported/Seaquest.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/games/supported/Seaquest.cpp.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/games/supported/Seaquest.cpp.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/games/supported/Seaquest.cpp.s
.PHONY : src/games/supported/Seaquest.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/os_dependent/AleSystemUNIX.o: src/os_dependent/AleSystemUNIX.cxx.o
.PHONY : src/os_dependent/AleSystemUNIX.o

# target to build an object file
src/os_dependent/AleSystemUNIX.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/AleSystemUNIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/AleSystemUNIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/AleSystemUNIX.cxx.o
.PHONY : src/os_dependent/AleSystemUNIX.cxx.o

src/os_dependent/AleSystemUNIX.i: src/os_dependent/AleSystemUNIX.cxx.i
.PHONY : src/os_dependent/AleSystemUNIX.i

# target to preprocess a source file
src/os_dependent/AleSystemUNIX.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/AleSystemUNIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/AleSystemUNIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/AleSystemUNIX.cxx.i
.PHONY : src/os_dependent/AleSystemUNIX.cxx.i

src/os_dependent/AleSystemUNIX.s: src/os_dependent/AleSystemUNIX.cxx.s
.PHONY : src/os_dependent/AleSystemUNIX.s

# target to generate assembly for a file
src/os_dependent/AleSystemUNIX.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/AleSystemUNIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/AleSystemUNIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/AleSystemUNIX.cxx.s
.PHONY : src/os_dependent/AleSystemUNIX.cxx.s

src/os_dependent/FSNodePOSIX.o: src/os_dependent/FSNodePOSIX.cxx.o
.PHONY : src/os_dependent/FSNodePOSIX.o

# target to build an object file
src/os_dependent/FSNodePOSIX.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/FSNodePOSIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/FSNodePOSIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/FSNodePOSIX.cxx.o
.PHONY : src/os_dependent/FSNodePOSIX.cxx.o

src/os_dependent/FSNodePOSIX.i: src/os_dependent/FSNodePOSIX.cxx.i
.PHONY : src/os_dependent/FSNodePOSIX.i

# target to preprocess a source file
src/os_dependent/FSNodePOSIX.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/FSNodePOSIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/FSNodePOSIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/FSNodePOSIX.cxx.i
.PHONY : src/os_dependent/FSNodePOSIX.cxx.i

src/os_dependent/FSNodePOSIX.s: src/os_dependent/FSNodePOSIX.cxx.s
.PHONY : src/os_dependent/FSNodePOSIX.s

# target to generate assembly for a file
src/os_dependent/FSNodePOSIX.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/FSNodePOSIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/FSNodePOSIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/FSNodePOSIX.cxx.s
.PHONY : src/os_dependent/FSNodePOSIX.cxx.s

src/os_dependent/SettingsUNIX.o: src/os_dependent/SettingsUNIX.cxx.o
.PHONY : src/os_dependent/SettingsUNIX.o

# target to build an object file
src/os_dependent/SettingsUNIX.cxx.o:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/SettingsUNIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/SettingsUNIX.cxx.o
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/SettingsUNIX.cxx.o
.PHONY : src/os_dependent/SettingsUNIX.cxx.o

src/os_dependent/SettingsUNIX.i: src/os_dependent/SettingsUNIX.cxx.i
.PHONY : src/os_dependent/SettingsUNIX.i

# target to preprocess a source file
src/os_dependent/SettingsUNIX.cxx.i:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/SettingsUNIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/SettingsUNIX.cxx.i
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/SettingsUNIX.cxx.i
.PHONY : src/os_dependent/SettingsUNIX.cxx.i

src/os_dependent/SettingsUNIX.s: src/os_dependent/SettingsUNIX.cxx.s
.PHONY : src/os_dependent/SettingsUNIX.s

# target to generate assembly for a file
src/os_dependent/SettingsUNIX.cxx.s:
	$(MAKE) -f CMakeFiles/ale-bin.dir/build.make CMakeFiles/ale-bin.dir/src/os_dependent/SettingsUNIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-c-lib.dir/build.make CMakeFiles/ale-c-lib.dir/src/os_dependent/SettingsUNIX.cxx.s
	$(MAKE) -f CMakeFiles/ale-lib.dir/build.make CMakeFiles/ale-lib.dir/src/os_dependent/SettingsUNIX.cxx.s
.PHONY : src/os_dependent/SettingsUNIX.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ale-bin"
	@echo "... ale-c-lib"
	@echo "... ale-lib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sharedLibraryInterfaceExample"
	@echo "... videoRecordingExample"
	@echo "... ale_python_interface/ale_c_wrapper.o"
	@echo "... ale_python_interface/ale_c_wrapper.i"
	@echo "... ale_python_interface/ale_c_wrapper.s"
	@echo "... doc/examples/sharedLibraryInterfaceExample.o"
	@echo "... doc/examples/sharedLibraryInterfaceExample.i"
	@echo "... doc/examples/sharedLibraryInterfaceExample.s"
	@echo "... doc/examples/videoRecordingExample.o"
	@echo "... doc/examples/videoRecordingExample.i"
	@echo "... doc/examples/videoRecordingExample.s"
	@echo "... src/ale_interface.o"
	@echo "... src/ale_interface.i"
	@echo "... src/ale_interface.s"
	@echo "... src/common/AleException.o"
	@echo "... src/common/AleException.i"
	@echo "... src/common/AleException.s"
	@echo "... src/common/ColourPalette.o"
	@echo "... src/common/ColourPalette.i"
	@echo "... src/common/ColourPalette.s"
	@echo "... src/common/Constants.o"
	@echo "... src/common/Constants.i"
	@echo "... src/common/Constants.s"
	@echo "... src/common/Log.o"
	@echo "... src/common/Log.i"
	@echo "... src/common/Log.s"
	@echo "... src/common/ScreenExporter.o"
	@echo "... src/common/ScreenExporter.i"
	@echo "... src/common/ScreenExporter.s"
	@echo "... src/common/SoundExporter.o"
	@echo "... src/common/SoundExporter.i"
	@echo "... src/common/SoundExporter.s"
	@echo "... src/common/SoundNull.o"
	@echo "... src/common/SoundNull.i"
	@echo "... src/common/SoundNull.s"
	@echo "... src/common/SoundSDL.o"
	@echo "... src/common/SoundSDL.i"
	@echo "... src/common/SoundSDL.s"
	@echo "... src/common/display_screen.o"
	@echo "... src/common/display_screen.i"
	@echo "... src/common/display_screen.s"
	@echo "... src/controllers/ale_controller.o"
	@echo "... src/controllers/ale_controller.i"
	@echo "... src/controllers/ale_controller.s"
	@echo "... src/controllers/fifo_controller.o"
	@echo "... src/controllers/fifo_controller.i"
	@echo "... src/controllers/fifo_controller.s"
	@echo "... src/controllers/rlglue_controller.o"
	@echo "... src/controllers/rlglue_controller.i"
	@echo "... src/controllers/rlglue_controller.s"
	@echo "... src/environment/AleSystem.o"
	@echo "... src/environment/AleSystem.i"
	@echo "... src/environment/AleSystem.s"
	@echo "... src/environment/Deserializer.o"
	@echo "... src/environment/Deserializer.i"
	@echo "... src/environment/Deserializer.s"
	@echo "... src/environment/FSNode.o"
	@echo "... src/environment/FSNode.i"
	@echo "... src/environment/FSNode.s"
	@echo "... src/environment/Random.o"
	@echo "... src/environment/Random.i"
	@echo "... src/environment/Random.s"
	@echo "... src/environment/RetroAgent.o"
	@echo "... src/environment/RetroAgent.i"
	@echo "... src/environment/RetroAgent.s"
	@echo "... src/environment/Serializer.o"
	@echo "... src/environment/Serializer.i"
	@echo "... src/environment/Serializer.s"
	@echo "... src/environment/Settings.o"
	@echo "... src/environment/Settings.i"
	@echo "... src/environment/Settings.s"
	@echo "... src/environment/ale_state.o"
	@echo "... src/environment/ale_state.i"
	@echo "... src/environment/ale_state.s"
	@echo "... src/environment/phosphor_blend.o"
	@echo "... src/environment/phosphor_blend.i"
	@echo "... src/environment/phosphor_blend.s"
	@echo "... src/environment/retro_environment.o"
	@echo "... src/environment/retro_environment.i"
	@echo "... src/environment/retro_environment.s"
	@echo "... src/external/TinyMT/tinymt32.o"
	@echo "... src/external/TinyMT/tinymt32.i"
	@echo "... src/external/TinyMT/tinymt32.s"
	@echo "... src/games/AtariSettings.o"
	@echo "... src/games/AtariSettings.i"
	@echo "... src/games/AtariSettings.s"
	@echo "... src/games/RomSettings.o"
	@echo "... src/games/RomSettings.i"
	@echo "... src/games/RomSettings.s"
	@echo "... src/games/RomUtils.o"
	@echo "... src/games/RomUtils.i"
	@echo "... src/games/RomUtils.s"
	@echo "... src/games/Roms.o"
	@echo "... src/games/Roms.i"
	@echo "... src/games/Roms.s"
	@echo "... src/games/SnesSettings.o"
	@echo "... src/games/SnesSettings.i"
	@echo "... src/games/SnesSettings.s"
	@echo "... src/games/supported/AtariCollection.o"
	@echo "... src/games/supported/AtariCollection.i"
	@echo "... src/games/supported/AtariCollection.s"
	@echo "... src/games/supported/Boxing.o"
	@echo "... src/games/supported/Boxing.i"
	@echo "... src/games/supported/Boxing.s"
	@echo "... src/games/supported/Breakout.o"
	@echo "... src/games/supported/Breakout.i"
	@echo "... src/games/supported/Breakout.s"
	@echo "... src/games/supported/MortalKombat.o"
	@echo "... src/games/supported/MortalKombat.i"
	@echo "... src/games/supported/MortalKombat.s"
	@echo "... src/games/supported/Seaquest.o"
	@echo "... src/games/supported/Seaquest.i"
	@echo "... src/games/supported/Seaquest.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/os_dependent/AleSystemUNIX.o"
	@echo "... src/os_dependent/AleSystemUNIX.i"
	@echo "... src/os_dependent/AleSystemUNIX.s"
	@echo "... src/os_dependent/FSNodePOSIX.o"
	@echo "... src/os_dependent/FSNodePOSIX.i"
	@echo "... src/os_dependent/FSNodePOSIX.s"
	@echo "... src/os_dependent/SettingsUNIX.o"
	@echo "... src/os_dependent/SettingsUNIX.i"
	@echo "... src/os_dependent/SettingsUNIX.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

